version: '3'

services:
  web:
    build: .
    command: bash -c "python api/manage.py makemigrations && python api/manage.py migrate && python api/manage.py runserver 0.0.0.0:8000"
    container_name: django_image_api
    volumes:
      - .:/api
    ports:
      - "8000:8000"